import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import {Carousel, Navbar} from 'flowbite-react'
import Link from 'next/link'

import Navigation from '../components/Navigation'

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Henry Marken</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>  
        
        <div className="h-screen w-full">
          <Carousel slide={false}>
            <Image src="/images/edmonton-fall-cropped.jpg" width={3200} height={1800} className="h-screen object-cover"/>
            <Image src="/images/sydney-eyes.jpg" width={3200} height={1800} className="h-screen object-cover"/>
            <Image src="/images/fall-path-cropped.jpg" width={3200} height={1800} className="h-screen object-cover"  />
            <Image src="/images/vancouver-night-cropped.jpg" width={3200} height={1800} className="h-screen object-cover" />
            <Image src="/images/orange-sunset-cropped.jpg" width={3200} height={1800} className="h-screen object-cover" />
            <Image src="/images/vancouver-flower-cropped.jpg" width={3200} height={1800}className="h-screen object-cover" />
          </Carousel>
        </div>

        <Navigation/>

        <div className="text-white">
          <div className="h-screen w-full rounded-none bg-gallery bg-center">
              <Link href="/gallery" className="text-center h-screen md:text-6xl text-4xl grid place-content-center md:float-left md:ml-20 md:font-semibold tracking-widest transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 duration-150">GALLERY</Link>
          </div>
          <div className="h-screen w-full rounded-none bg-photoshoots bg-center">
              <Link href="/photoshoots" className="text-center h-screen md:text-6xl text-4xl grid place-content-center md:float-right md:mr-20 md:font-semibold tracking-widest transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 duration-150">PHOTOSHOOTS</Link>
          </div>
          <div className="h-screen w-full rounded-none bg-about bg-center">
              <Link href="/about" className="text-center h-screen md:text-6xl text-4xl grid place-content-center md:float-left md:ml-20 md:font-semibold tracking-widest transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 duration-150">ABOUT</Link>
          </div>
          <div className="h-screen w-full rounded-none bg-contact bg-center">
              <Link href="/contact" className="text-center h-screen md:text-6xl text-4xl grid place-content-center md:float-right md:mr-20 md:font-semibold tracking-widest transition ease-in-out delay-150  hover:-translate-y-1 hover:scale-110 duration-150">CONTACT</Link>
          </div>
        </div>
      </main>
    </>
  )
}
